### ISSUE TITLE
re-implement memories

### ISSUE THREAD

**Issue by freebsdgirl** [freebsdgirl/kirishima#30]
Now we get to one of the core things that Kirsihima needs to be... Kirishima.

The code already exists for this and we can re-use a lot of it, but this time

- [ ] proper test coverage
- [ ] per-user memory storage (last step, let's just plan for it for now)
- [x] ensure the collection is properly created if it doesn't already exist (i.e., with embedding functions specified)
- [ ] create better helper scripts for managing memories
- [x] lean harder into pydantic when possible

**Comment by freebsdgirl** [comment]
still have a few more tests to write, but i need to take a breather. leaving progress here so i'm not left wondering where tf i was earlier.

i've tested /memory/semantic manually, so i know the code works - just haven't written the tests. put and patch have not yet been tested at all yet.

```
endpoint: GET /memory/semantic
args:
    text: str (semantic search)
    component: str (optional) (ex: proxy, imessage)
    mode: str (optional) (ex: nsfw, default, work)
    priority: float (optional) (ge=0, le=1)
    limit: int (optional)
returns:
    List[MemoryView]

endpoint: PUT /memory/{memory_id}
args:
    memory_id: str
    request_data: MemoryEntry
returns:
    MemoryView

endpoint: PATCH /memory/{memory_id}
args:
    memory_id: str
    patch: MemoryPatch
returns:
    MemoryView


```
